- packages/hs-react-ui/src/components/Button/Button.stories.tsx
- packages/hs-react-ui/src/components/Button/Button.tsx
- packages/hs-react-ui/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap
- packages/hs-react-ui/src/components/Dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap
- packages/hs-react-ui/src/components/InteractionFeedback/InteractionFeedback.stories.tsx
- packages/hs-react-ui/src/components/InteractionFeedback/InteractionFeedback.tsx
Add two types of feedback to Button, simple (darkening by css), and ripple (utilizing
InteractionFeedback). Updated InteractionFeedback to take a color prop. This fill can still be
overridden by transitionProps.
> feat(button, interactionfeedback): add InteractionFeedback wrapper around Button

- packages/hs-react-ui/src/components/Button/Button.tsx
- packages/hs-react-ui/src/components/InteractionFeedback/InteractionFeedback.tsx
Buttons are by default display: inline-block, but when the feedback type was set to "ripple" it was
wrapped in a div, setting them to display:block at the outer most layer
> fix(button and interactionfeedback): style the InteractionFeedback for the Button to inline-block

- packages/foundry-react-ui/src/components/Dropdown/Dropdown.stories.tsx
- packages/foundry-react-ui/src/components/Dropdown/Dropdown.tsx
Optionally, based on rememberScrollPosition, the dropdown options box will scroll to where it was previously scrolled to. This is useful in many standard cases, but when dynamic options are being passed in, remembering the scroll position can be harmful to the UX - hence the optional prop.
✅ Closes: #214
> #214 fix: 🐛 Scroll position now persists when open/closing options

- packages/foundry-react-ui/.storybook/docPagesStyle.css
pre-wrapping the styled-components subcomonent definition in the prop
table makes it much easier to read
✅ Closes: #212
> #212 docs: ✏️ Format docs table to make component code more readable

- src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap
- src/components/Card/Card.tsx
- src/components/Card/__tests__/__snapshots__/Card.test.tsx.snap
- src/components/Dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap
- src/components/Tag/__tests__/__snapshots__/Tag.test.tsx.snap
- src/utils/styles.ts
Fixes #233 by adding the `contain: layout;` style to the Card component's top-level container.
Since the `StyledFeedbackContainer` has an absolute position, the clickable element for the ripple interaction fills the screen when the `CardContainer` component is lacking a layout restriction. When the `elevation` prop > 0, the `box-shadow` on the Card container is replaced with a `filter: drop-shadow`, which provides this restriction. Adding a layout containment to the `CardContainer` component restricts this positioning with intention and does so for all elevation values.
Some helpful info:
- [CSS Positioning](https://www.w3schools.com/css/css_positioning.asp)
- [Why does applying a CSS-Filter on the parent break the child positioning?](https://stackoverflow.com/a/52937920)
> #233 Set layout containment for Card component

- .storybook/headstormTheme.js
- src/components/Examples/GlobalStyles.stories.tsx
- src/components/RangeSlider/__tests__/__snapshots__/RangeSlider.test.tsx.snap
- src/context/index.tsx
- src/enums/fonts.ts
Previously, Montserrat was used on every foundry-ui component by default. It could be overwritten by another using our globalStyles api, but the font would still be loaded by Google Fonts. This change removes Montserrat and its loading in favor of an OS-default font: Arial. It also looks better and Headstorm doesn't use Montserrat anymore anyway.
complete #250
> feat(globalstyles): reduce load times by using Arial instead of Montserrat

- src/components/Divider/Divider.tsx
Like the Container, the Divider should be exported to serve as a base for the Styled subcomponent
props
closes #280
> fix(divider): adds the divider subcomponent to the module exports

- .github/workflows/buildCheck.yml
- package.json
Coverage is now only generated in the GH action on buildCheck and stored in artifacts
> build(coverage): stop generating coverage while testing during pre-push locally

- jest.config.js
- package.json
Coverage should only be collected (updated) during deployments in the GH Actions CI runner. This sets the default to false, and ensures only `test-ci` runs the coverage collection.
> Stop collecting coverage by default for jest tests

- src/components/Button/Button.tsx
Previously, the skeleton props were typed but not applied to the shimmer. This change also renames
the prop - but t
fixes #322
> fix(button): skeleton props object is now correctly spread on skeleton shimmer

- .storybook/main.ts
This change seems to have fixed some compatibility issues involving Webpack5 that result in a failed build upon fresh install/build of the repo.
> Changed default webpack builder to Webpack4 from Webpack5

- src/context/index.tsx
In order to give users more flexibility on how they use the analytics function, all arguments are now optional
> fix(analyticsfunction): made all param types optional

- src/index.ts
Functions for calculating shadows from elevation numbers are now available for use outside of internal Foundry CSS
> fix(exports): add style-related util functions to exports

- src/components/Toggle/__tests__/Toggle.test.tsx
- src/context/index.tsx
analytics props can be undefined, so we should access it with that in mind
> fix(analytics): safely access props, as it can be undefined

- src/components/Button/Button.tsx
- src/components/Table/Table.stories.tsx
- src/components/Table/Table.tsx
- src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
- src/components/Table/types.ts
- src/components/commonTypes.ts
**This PR accomplishes the following:** 
- Adds type support for custom component builders with props for columns in the `Columns` type, for things like cellComponent, headerCellComponent, etc, while retaining support for StyledComponents (see `ComponentBuilder`)
- Fixes group headers appearance in responsive view
- Makes custom sortFunctions functional in both directions, and extracts reusable comparison code into the `compareEntries` function, fixes group sorting
- Fixes sorting on the Table storyboard
- Fixes responsive view 
- Fixes passing in of rowProps StyledRow for non-grouped Table's
- Allows for styling of the ResponsiveHeaderCell, and wraps cell in CellContainer (which contains both the ResponsiveHeaderCell if in responsive mode, and the Cell).
- Change type of table `data` to …
> Fixes #379 #434

- src/components/Dropdown/Dropdown.tsx
Bug: If a user selects an option from the dropdown when it is searchable and multiple options may be chosen, the user is unable to close the dropdown.
Changes: Modified blur logic.
> 448 dropdown blur when multi search fix

- src/components/RangeSlider/RangeSlider.stories.tsx
- src/components/RangeSlider/RangeSlider.tsx
- src/components/RangeSlider/types.ts
- This PR implements isReadOnly prop to the RangeSlider.
-This prop ensures that the RangeSlider cannot be used to change the value in readOnly mode.
- This feature can be really useful when implementing the RangeSlider and ensuring that only certain users can edit the value on the RangeSlider.
> Implemented isReadOnly prop for RangeSlider component

- src/components/Spotlight/Spotlight.tsx
Instead of always trying to scroll the window to highlight the target, it now finds the nearest
scrollable element and scrolls that instead. Many times, that will be the window/html element
fixes #481
> fix(spotlight, usescrollobserver): automatically scroll nearest scrollable element

- src/components/Modal/Modal.tsx
Fix for issue #485 
When Modal onClickOutside=false, pressing the Esc key will cause the modal to be hidden when the expected behavior is that an Esc key press would do nothing.
Tests pass and no known issues have arisen.
> 485: When Modal onClickOutside=false Esc key causes failure

- src/components/Table/Table.tsx
Previously, the table would put all capitalized words ahead of lowercased words
Fix #479
> fix(table): default table sorting now correctly ignores capitalized letters in sort
